version: '3'
services:

  db:
    image: postgres   # coldis/infrastructure-transactional-repository
    environment:
      - DATABASE_NAME=test
      - ENABLE_JSON_CAST=true
      - ENABLE_UNACCENT=true
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - REPLICATOR_USER_NAME=replicator
      - REPLICATOR_USER_PASSWORD=test
      - USER_NAME=test
      - USER_PASSWORD=test
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - supersim
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

#  artemis:
#    image: coldis/infrastructure-messaging-service
#    environment:
#      - ARTEMIS_USERNAME=test
#      - ARTEMIS_PASSWORD=test
#      - ARTEMIS_PERF_JOURNAL=ALWAYS
#      - ENVIRONMENT=development
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#      - "61613:61613"
#    container_name: artemis
#    networks:
#      - supersim
#    healthcheck:
#      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#    restart: always

  application:
    build: 
      context: .
    image: java-app
    stdin_open: true 
    tty: true
    container_name: application
    networks:
      - supersim
    ports:
      - 8080:8080
    depends_on:
      - db
#      - artemis

networks:
  supersim:
    driver: bridge



